#ifndef CONSTANT_H
#define CONSTANT_H

#define RECURSIVE_LIMIT 2
#define AIR_D 1.0f
#define PI 3.14159265
#define AMBIENT_ILLUSION 1.0f
#define LIGHT_POWER 20.0f
#define OFFSET 0.00001f
#define BOX_OFFSET 0.00f
#define LAYER_LIMIT 10
#define BLOCK_MINIMUM 10
#define SAME_POINT_THRESHOLD 0.0001f
#define KDTREE_MEDIAN
//#define KDTREE_SAH
#define TRAVERSE_COST 2.0f
#define INTERSECTION_COST 1.12f
#define OVERLAP_COST 0.0f

#endif